### ISSUE TITLE
access commit.files or commit.lines will get an error: AttributeError: 'NoneType' object has no attribute 'repo'

### ISSUE THREAD

**Issue by hcwang** [ishepard/pydriller#283]
**Describe the bug**

After upgrade from 2.5 to 2.5.1, the below code will raise exception.

**To Reproduce**

The below code:
```python
commits = list(Repository(".",only_no_merge=True).traverse_commits())
commits[0].files
commits[0].lines
```
will raise:
 
> AttributeError: 'NoneType' object has no attribute 'repo'

**OS Version:**

monarch

**Comment by ishepard** [comment]
Thanks for raising the issue! 
I just checked and this code works:
```
from pydriller import Repository

for commit in Repository("test-repos/small_repo", only_no_merge=True).traverse_commits():
    print(commit.lines)
    print(commit.files)
```

but this code doesn't work:
```
commits = list(Repository("test-repos/small_repo",only_no_merge=True).traverse_commits())
commits[0].files
commits[0].lines
```

Not sure why, we'll have to check. I will put this issue as a bug and PR are welcome

**Comment by ishepard** [comment]
The reason is that the object is inside a context manager, so it will get destroyed after the loop. 

I don't see a good solution to this, other than just iterating over the commits rather than putting them in a list.

**Comment by hcwang** [comment]
Any plan to fix this issue? thanks.

**Comment by tanistheta** [comment]
I looked into this. The naive fix is falling back to self._c_object.repo when self._conf.get('git') is None, now this works for local repos, since the .git directory never goes away but it's not safe for the remote/cloned-repo case: once _prep_repo's context manager exits, self._tmp_dir.cleanup() deletes the cloned directory from disk (confirmed with os.path.exists() returning False), yet self._c_object.repo.git.diff(...) still succeeded and returned correct output in my testing. That's almost certainly GitPython or the OS keeping file handles alive briefly after the directory entry is removed, which is a known Windows behavior. It's not something to rely on, since it could behave differently on Linux CI runners or under different timing, and would fail unpredictably rather than cleanly.
A more robust direction is probably eager stats computation: caching _stats()'s result at Commit construction time, while the repo is still guaranteed live, instead of lazily on first access. That avoids depending on the repo surviving past the context manager at all. I haven't tested the performance cost of that yet, since every commit would pay for stats computation even if the caller never needs it. Wanted to share the finding rather than sit on it. Happy to pick this up further if it's useful.
